on: push
  branches:
    - master
name: Build and Deploy
jobs:
  buildImageAndDeployToAks:
    name: Build Docker image and deploy to Azure Kubernetes Service
    runs-on: ubuntu-latest
    steps:
    - name: Set some env vars
      run: echo ::set-env name=GITHUB_SHA_SHORT::$(echo $GITHUB_SHA | cut -c 1-6)
    - uses: actions/checkout@master
    - name: Build Docker image
      uses: docker://docker:stable
      with:
        args: build -t aks-example-octozen .
    - name: Load AKS kube credentials
      uses: docker://swinton/azure
      env:
        AZURE_SERVICE_APP_ID: ${{ secrets.AZURE_SERVICE_APP_ID }}
        AZURE_SERVICE_PASSWORD: ${{ secrets.AZURE_SERVICE_PASSWORD }}
        AZURE_SERVICE_TENANT: ${{ secrets.AZURE_SERVICE_TENANT }}
      with:
        args: aks get-credentials --resource-group kardashian --name kardashian
    - name: Tag and push image to ACR
      uses: azure/container-actions/docker-login@master
      with:
        login-server: shipyard.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    - run: |
        echo GITHUB_SHA_SHORT is $GITHUB_SHA_SHORT
        docker tag aks-example-octozen shipyard.azurecr.io/aks-example-octozen:$GITHUB_SHA_SHORT
        docker push shipyard.azurecr.io/aks-example-octozen:$GITHUB_SHA_SHORT
    - name: Deploy to AKS
      uses: docker://gcr.io/cloud-builders/kubectl
      with:
        entrypoint: sh
        args: -l -c "kubectl set image deployment aks-example-octozen aks-example-octozen=shipyard.azurecr.io/aks-example-octozen:$GITHUB_SHA_SHORT"
